#!/usr/bin/env python3

import sys
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parent

if len(sys.argv) < 2:
    print("Usage: gdd [pull|push]")
    sys.exit(1)

cmd = sys.argv[1]

if cmd == "pull":
    subprocess.run(["python3", ROOT / "gd_pull.py"] + sys.argv[2:])

elif cmd == "push":
    subprocess.run(["python3", ROOT / "gd_push.py"] + sys.argv[2:])

else:
    print("Unknown command")
